server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: adguard-querylog
    static_configs:
      - targets:
          - localhost
        labels:
          job: adguard-querylog
          host: ${HOSTNAME}
          __path__: __ADGUARD_QUERYLOG_PATH__

  - job_name: adguard-journal
    journal:
      path: /var/log/journal
      max_age: 12h
      labels:
        job: adguard-journal
        host: ${HOSTNAME}
    relabel_configs:
      - source_labels: [__journal__systemd_unit]
        regex: __ADGUARD_SYSTEMD_UNIT__
        action: keep
      - source_labels: [__journal__priority_keyword]
        target_label: level
      - source_labels: [__journal__hostname]
        target_label: node
